CREATE TABLE IF NOT EXISTS mpa_ratings (
                                           id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           name VARCHAR(10) NOT NULL
    );

CREATE TABLE IF NOT EXISTS films (
                                     id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name         VARCHAR(255) NOT NULL,
    description  VARCHAR(200),
    release_date DATE,
    duration     INTEGER,
    mpa_id       INTEGER REFERENCES mpa_ratings(id)
    );

CREATE TABLE IF NOT EXISTS genres (
                                      id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS film_genres (
                                           film_id  INTEGER REFERENCES films(id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres(id),
    PRIMARY KEY (film_id, genre_id)
    );

CREATE TABLE IF NOT EXISTS users (
                                     id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email    VARCHAR(255) NOT NULL,
    login    VARCHAR(255) NOT NULL,
    name     VARCHAR(255),
    birthday DATE
    );

CREATE TABLE IF NOT EXISTS likes (
                                     film_id INTEGER REFERENCES films(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );

CREATE TABLE IF NOT EXISTS friendships (
                                           user_id   INTEGER REFERENCES users(id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    status    VARCHAR(20) NOT NULL DEFAULT 'UNCONFIRMED',
    PRIMARY KEY (user_id, friend_id)
    );

CREATE TABLE IF NOT EXISTS reviews (
                                       review_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       content    TEXT NOT NULL,
                                       is_positive BOOLEAN NOT NULL,
                                       user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    film_id    INTEGER NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    useful     INTEGER NOT NULL DEFAULT 0
    );

CREATE TABLE IF NOT EXISTS review_ratings (
                                              review_id BIGINT NOT NULL REFERENCES reviews(review_id) ON DELETE CASCADE,
    user_id   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    is_like   BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id)
    );

CREATE INDEX IF NOT EXISTS idx_reviews_film_useful
    ON reviews (film_id, useful DESC);

CREATE INDEX IF NOT EXISTS idx_reviews_user_id
    ON reviews (user_id);

CREATE INDEX IF NOT EXISTS idx_review_ratings_user_id
    ON review_ratings (user_id);

CREATE TABLE IF NOT EXISTS events (
                                      event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      event_timestamp BIGINT NOT NULL,
                                      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_type VARCHAR(10) NOT NULL,
    operation VARCHAR(10) NOT NULL,
    entity_id BIGINT NOT NULL,
    CONSTRAINT chk_events_type
    CHECK (event_type IN ('LIKE', 'REVIEW', 'FRIEND')),
    CONSTRAINT chk_events_operation
    CHECK (operation IN ('ADD', 'UPDATE', 'REMOVE'))
    );

CREATE INDEX IF NOT EXISTS idx_events_user_timestamp
    ON events (user_id, event_timestamp, event_id);